# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c750581c6a871196cbe78f9cefbdb5a683f3d9d6416513049c9fc7ca4f6bc89f1a7bc79913bcc4c321e60f5ede521ecafbeea4040bb8d8ebf33eeff6a56f5c09

test:
  secret_key_base: 0bd71908c6f4a5f08748f7d1e1261b67350747bba5ce81a066436be8764c4f8bce9fa1c28fc20a444799c92e57bcc4ad882b594eb1e495e14a1b584d403ed57f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
